# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: update-bandit-in-readme
        name: Update Bandit security scan result in README.md
        entry: ./scripts/update_bandit_in_readme.sh
        language: script
        pass_filenames: false
        always_run: true
