name: Action Onboarding Consistency Check

on:
  pull_request:
    paths:
      - 'playbooks/**'
      - 'scripts/**'
      - 'config/actions.yaml'
      - 'scripts/check_action_onboarding.py'
      - '.github/workflows/onboarding-check.yml'
  push:
    branches: [ main ]
    paths:
      - 'playbooks/**'
      - 'scripts/**'
      - 'config/actions.yaml'
      - 'scripts/check_action_onboarding.py'
      - '.github/workflows/onboarding-check.yml'

jobs:
  onboarding-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Lint with flake8
        run: |
          . venv/bin/activate || python -m venv venv
          . venv/bin/activate && pip install flake8 black
          . venv/bin/activate && flake8 src/ tests/
      - name: Check formatting with black
        run: |
          . venv/bin/activate && black --check src/ tests/
      - name: Run onboarding/auto-discovery check
        run: |
          chmod +x scripts/check_action_onboarding.py
          . venv/bin/activate && scripts/check_action_onboarding.py
      - name: Run tests with coverage
        run: |
          . venv/bin/activate && pip install pytest pytest-cov
          . venv/bin/activate && pytest --cov=src --cov-report=xml --cov-report=term --maxfail=1 --disable-warnings -v
      - name: Upload coverage to GitHub (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
